public class EncumberenceWrapper {
    public String cde_Level_Care;
    public String cde_Status_Encmbr;
    public String cde_Type_Unit_Care;
    public String cnt_Hour_Attnd_Actual;
    public String cnt_Hour_Care;
    public String idn_Auth;
    public String dte_Care;
    public String createdbyid;
    public String createddate;
    public String nbr_Seq_Hist;
	public String lastmodifieddate;
    public String lastmodifiedbyid;
    public String ind_0_36_months;
}