public  class FailBatchLogPOCO {
    public String IDN_EXTNL {get; set;}
    public String Batch_Name {get; set;}
    public String Status {get; set;}
    public String Records_Processed {get; set;}
    public String Records_Failed {get; set;}
    public String Error_Message {get; set;}
    public String RunDate {get; set;}
    public String start_time {get; set;}
    public String end_time {get; set;} 

}