public without sharing class IndivEmploymeentWrapper {

    @auraEnabled
    public string indivName;
    
     @auraEnabled
    public string clientId;
    
     @auraEnabled
    public string effectiveBeginDate;
    
     @auraEnabled
    public string recordTypeName;
    
     @auraEnabled
    public string employer;
    
     @auraEnabled
    public string address;
    
     @auraEnabled
    public string employerPhone;
    
     @auraEnabled
    public string estimatedIncome;
    
     @auraEnabled
    public string grossMonthlyIncome;
    
     @auraEnabled
    public string employmentExpense;
    
     @auraEnabled
    public string eploymentId;
    
     @auraEnabled
    public Id indivSfid;
    
     @auraEnabled
    public Id employmentSfid;
    
    public IndivEmploymeentWrapper(){
        
    }
}