public class PeakResultWrapper {
    @auraEnabled
    public String queuecounty;
    @auraEnabled
    public String appId;
    @auraEnabled        
    public String queueId;
    @auraEnabled 
    public String queuestatus;
    @auraEnabled 
    public String firstName;
    @auraEnabled 
    public String lstName;
    @auraEnabled 
    public String trackingNumber;
    @auraEnabled 
    public Date queueReceivedDate;
    @auraEnabled 
    public String queueCase;
    @auraEnabled 
    public String queueReason;
    
    public PeakResultWrapper(){
    }
}