public class sidmodResponseWrapper {
    @auraEnabled
    public string firstName;
    @auraEnabled
    public string middleName;
    @auraEnabled
    public string lastName;
    @auraEnabled
    public string gender;
    @auraEnabled
    public string dateOfBirth;
    @auraEnabled
    public string ssn;
    @auraEnabled
    public string stateId;
    @auraEnabled
    public string alienRegNumber;
    @auraEnabled
    public string title;
    @auraEnabled
    public string score;
    @auraEnabled
    public string dateOfDeath;
    
    

}