id: ccare_data_collection
name: ccare_data_collection
version: 1.2.2
description: ''
model: null
model_error: null
task_type: deterministic
system_prompt: ''
max_turns: 10
code: SEE_FILE:tasks/python/ccare_data_collection.py
timeout: 300
allowed_tools:
- tool: getproviderdata
knowledge_base_scope: null
tags:
- Child Care
max_tokens: null
response: prose
created_at: '2026-08-25T16:07:17.216686Z'
updated_at: '2026-10-05T16:46:00.812622Z'
